title: My sample book
author: The Jupyter Book Community
logo: logo.png

execute:
  execute_notebooks: force

html:
  use_issues_button: false
  use_repository_button: false
  theme:
    name: sphinx_book_theme
    options:
      navigation_depth: 3
      show_navbar_depth: 3
      collapse_navigation: false